version: '3'
services:
  service:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "8085:8085"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
networks:
  default:
    external:
      name: project-local-network